# Generated by Django 2.0.3 on 2018-06-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Unknown')], max_length=1)),
                ('survived', models.BooleanField(default=False)),
                ('ticket_class', models.IntegerField(choices=[('0', 'Unknown'), ('1', '1st Class'), ('2', '2nd Class'), ('3', '3rd Class')], default=3)),
                ('embarked', models.CharField(blank=True, choices=[('S', 'Southampton'), ('C', 'Cherbourg'), ('Q', 'Queenstown'), ('', 'Unknown')], max_length=1)),
                ('age', models.FloatField(blank=True)),
            ],
        ),
    ]
